{
 "title": "kafka-consumer",
 "tags": [ "kafka" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kafka_server_replicamanager_partitioncount, cluster)"
   },
   {
    "name": "consumergroup",
    "label": "consumergroup",
    "query": "label_values(kafka_consumergroup_lag{cluster=~\"$cluster\"}, consumergroup)"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "label_values(kafka_consumergroup_lag{cluster=~\"$cluster\",consumergroup=~\"$consumergroup\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "message consumed /s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{cluster=~\"$cluster\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{cluster=~\"$cluster\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"}[10m])) by (partition) / 10 / 60",
     "legendFormat": "partition {{partition}}"
    }
   ]
  },
  {
   "title": "consume lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{cluster=~\"$cluster\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"})",
     "legendFormat": "total"
    },
    {
     "expr": "topk(20, sum(kafka_consumergroup_lag{cluster=~\"$cluster\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (partition))",
     "legendFormat": "partition {{partition}}"
    }
   ]
  },
  {
   "title": "consumer latest offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{cluster=~\"$cluster\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"})\tby (partition)",
     "legendFormat": "partition {{partition}}"
    }
   ]
  },
  {
   "title": "topic latest offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(kafka_log_log_logendoffset{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition)) / (count(kafka_log_log_logendoffset{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition))",
     "legendFormat": "partition {{partition}}"
    }
   ]
  }
 ]
}