{
 "title": "kafka-cluster",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kafka_server_replicamanager_partitioncount, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "brokers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kafka_log_log_size{cluster=~\"$cluster\"}) by (instance))",
     "legendFormat": "brokers"
    },
    {
     "expr": "kafka_server_kafkaserver_brokerstate{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}} state"
    }
   ]
  },
  {
   "title": "topics/partitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kafka_log_log_size{cluster=~\"$cluster\"}) by (topic))",
     "legendFormat": "topics"
    },
    {
     "expr": "sum(count(kafka_log_log_size{cluster=~\"$cluster\"}) by (topic,partition))",
     "legendFormat": "partitions"
    }
   ]
  },
  {
   "title": "partitions by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kafka_log_log_size{cluster=~\"$cluster\",topic!=\"\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "partitions by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, count(kafka_log_log_size{cluster=~\"$cluster\",topic!=\"\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "data size by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "data size by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(kafka_log_log_size{cluster=~\"$cluster\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "message in /s by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_messagesin_total{cluster=~\"$cluster\",topic=\"\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_messagesin_total{cluster=~\"$cluster\",topic=\"\"}[10m])) by (instance) / 10 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "message in /s by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(delta(kafka_server_brokertopicmetrics_messagesin_total{cluster=~\"$cluster\",topic!=\"\"}[10m]) > 0) by (topic)) / 10 / 60",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "bytes in by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesin_total{cluster=~\"$cluster\",topic=\"\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "delta(kafka_server_brokertopicmetrics_bytesin_total{cluster=~\"$cluster\",topic=\"\"}[10m]) / 10 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "bytes in by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(delta(kafka_server_brokertopicmetrics_bytesin_total{cluster=~\"$cluster\",topic!=\"\"}[10m]) > 0) by (topic)) / 10 / 60",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "bytes out by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesout_total{cluster=~\"$cluster\",topic=\"\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "delta(kafka_server_brokertopicmetrics_bytesout_total{cluster=~\"$cluster\",topic=\"\"}[10m]) / 10 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "bytes out by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(delta(kafka_server_brokertopicmetrics_bytesout_total{cluster=~\"$cluster\",topic!=\"\"}[10m]) > 0) by (topic)) / 10 / 60",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "under replicated by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{cluster=~\"$cluster\"} > 0)",
     "legendFormat": "total"
    },
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions{cluster=~\"$cluster\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "under replicated by topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{cluster=~\"$cluster\"} > 0)",
     "legendFormat": "total"
    },
    {
     "expr": "topk(20, count(kafka_topic_partition_under_replicated_partition{cluster=~\"$cluster\"} > 0) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "offline replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_offlinereplicacount{cluster=~\"$cluster\"} > 0)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(kafka_server_replicamanager_offlinereplicacount{cluster=~\"$cluster\"} > 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "top lagged consumers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(kafka_consumergroup_lag{cluster=~\"$cluster\"}) by (consumergroup, topic))",
     "legendFormat": "{{consumergroup}}/{{topic}}"
    }
   ]
  }
 ]
}