{
 "title": "kafka-topic",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kafka_server_replicamanager_partitioncount, cluster)"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "label_values(kafka_server_brokertopicmetrics_messagesin_total{cluster=~\"$cluster\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "replicas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kafka_log_log_size{cluster=~\"$cluster\",topic=~\"$topic\"}) / count(sum(kafka_log_log_size{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition))"
    }
   ]
  },
  {
   "title": "partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(kafka_log_log_size{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition))"
    }
   ]
  },
  {
   "title": "partitions by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count(kafka_log_log_size{cluster=~\"$cluster\",topic=~\"$topic\"}))",
     "legendFormat": "total"
    },
    {
     "expr": "count(kafka_log_log_size{cluster=~\"$cluster\",topic=~\"$topic\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "message in /s by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_messagesin_total{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_messagesin_total{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) by (instance) / 10 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "data size by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\",topic=~\"$topic\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\",topic=~\"$topic\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "data size by partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "bytes in by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesin_total{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesin_total{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) by (instance) / 10 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "bytes out by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesout_total{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesout_total{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) by (instance) / 10 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "log start offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_logstartoffset{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition) / (count(kafka_log_log_logstartoffset{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition))",
     "legendFormat": "partition {{partition}}"
    }
   ]
  },
  {
   "title": "log end offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_logendoffset{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition) / (count(kafka_log_log_logendoffset{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition))",
     "legendFormat": "partition {{partition}}"
    }
   ]
  },
  {
   "title": "consume rate /s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) by (consumergroup) / 10 / 60",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "consume lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{cluster=~\"$cluster\",topic=~\"$topic\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "under replicated by partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{cluster=~\"$cluster\",topic=~\"$topic\"} > 0) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "under replicated by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{cluster=~\"$cluster\",topic=~\"$topic\"} > 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}