{
 "title": "kafka-broker",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kafka_server_replicamanager_partitioncount, cluster)"
   },
   {
    "name": "broker",
    "label": "broker",
    "query": "label_values(kafka_server_replicamanager_partitioncount{cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "topics",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(kafka_log_log_size{cluster=~\"$cluster\",instance=~\"$broker\"}) by (topic))"
    }
   ]
  },
  {
   "title": "partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kafka_log_log_size{cluster=~\"$cluster\",instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "partitions by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sort_desc(count(kafka_log_log_size{cluster=~\"$cluster\",instance=~\"$broker\"}) by (topic)))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "data size by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\",instance=~\"$broker\"} > 0)",
     "legendFormat": "total"
    },
    {
     "expr": "topk(20, sum(kafka_log_log_size{cluster=~\"$cluster\",instance=~\"$broker\"} > 0) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "message in /s by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_messagesin_total{cluster=~\"$cluster\",instance=~\"$broker\",topic=\"\"}[10m]) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "topk(20, sum(delta(kafka_server_brokertopicmetrics_messagesin_total{cluster=~\"$cluster\",instance=~\"$broker\",topic!=\"\"}[10m])) by (topic)) / 10 / 60",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "bytes in by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesin_total{cluster=~\"$cluster\",instance=~\"$broker\",topic=\"\"}[10m]) > 0) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "topk(20, sum(delta(kafka_server_brokertopicmetrics_bytesin_total{cluster=~\"$cluster\",instance=~\"$broker\",topic!=\"\"}[10m]) > 0) by (topic)) / 10 / 60",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "bytes out by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesout_total{cluster=~\"$cluster\",instance=~\"$broker\",topic=\"\"}[10m]) > 0) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "topk(20, sum(delta(kafka_server_brokertopicmetrics_bytesout_total{cluster=~\"$cluster\",instance=~\"$broker\",topic!=\"\"}[10m]) > 0) by (topic)) / 10 / 60",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "offline replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_offlinereplicacount{cluster=~\"$cluster\",instance=~\"$broker\"} > 0)"
    }
   ]
  },
  {
   "title": "under replicated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions{cluster=~\"$cluster\",instance=~\"$broker\"}",
     "legendFormat": "under replicated"
    }
   ]
  },
  {
   "title": "under replicated by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{cluster=~\"$cluster\",instance=~\"$broker\"} > 0)",
     "legendFormat": "total"
    },
    {
     "expr": "topk(20, sum(kafka_topic_partition_under_replicated_partition{cluster=~\"$cluster\",instance=~\"$broker\"} > 0) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}